- src/constants/modules.ts
- src/modules/land-works/api.ts
- src/modules/land-works/components/land-works-card-explore-view/index.tsx
- src/modules/land-works/components/land-works-card-single-view/index.tsx
- src/modules/land-works/components/land-works-card/index.tsx
- src/modules/land-works/views/list-property-view/index.tsx
- src/utils.ts
* List: show proper default max & max future periods
* Property: show always the configured periods
Fixes #none
**Checklist**
> fix(properties): always show default periods

- src/design-system/Button/button-styles.ts
- src/modules/land-works/components/land-works-card-single-view/index.scss
- src/modules/land-works/views/single-land-view/index.scss
- src/modules/land-works/views/single-land-view/index.tsx
- src/styles/button.scss
- src/styles/index.scss
> [233] refactoring header buttons

- src/modules/land-works/views/single-land-view/index.tsx
> 344 / handleDelist function call

- src/modules/land-works/components/land-claim-history/index.tsx
- src/modules/land-works/components/land-my-properties-history/index.tsx
- src/modules/land-works/components/land-my-properties-history/styled.tsx
- src/modules/land-works/views/my-properties-view/index.tsx
Added rent history to my properties, fixed 'no claim history' color
> [EXTRA] some fixes

- src/modules/land-works/components/lands-claim-modal/index.tsx
branch name is wrong. this closes #361
> [261] change max clim selected assets const

- src/modules/land-works/components/land-works-input/index.tsx
Can be tested on the price input in listing and edit listing modal
> 357 - Remove input scroll on number inputs

- src/modules/land-works/views/single-land-view/index.tsx
> refactor: remove unused variable

- src/modules/land-works/views/single-land-view/index.tsx
- src/wallets/wallet.tsx
Call order functions:
1.  no active rent - delist & withdraw , handeDelist()
2.  active rent - delist, handleDelist()
3. delisted & actie - button disabled
4. delisted & no active rent - withdraw, handleWithDraw()
Open modal when you have a listed property which you have delisted but there is no active rent
> [EXTRA] fix function call & show modal

- src/modules/land-works/api.ts
- src/modules/land-works/components/land-my-properties-history/index.tsx
- src/utils.ts
* The renter will always be the same, so this information is not necessary to be shown
Fixes #none
**Checklist**
> fix(my-rent-history): show property instead of renter

- src/modules/land-works/components/land-works-card-history/index.tsx
fixed update operator
none
when we call the contract, the table is updated and rendered
**Checklist**
> fix table cell rerender

- src/modules/land-works/components/land-single-card-loader/index.tsx
- src/modules/land-works/components/land-works-list-input-dropdown/index.tsx
- src/modules/land-works/components/list-new-property/index.tsx
`xs`, `direction` of `Grid` container
none
**Checklist**
> [FIX] grid console errors

- src/modules/land-works/views/explore-view/index.tsx
Toggle currency when the "Mine only" toggle on
Fixes #375 
**Checklist**
> 375 / explore filters

- src/modules/land-works/components/land-claim-history/index.tsx
- src/modules/land-works/components/land-table-tx-hash/index.tsx
* apply styling
Fixes #none
**Checklist**
> fix(claim-history): tx hash style

- src/modules/land-works/components/land-works-list-card/index.tsx
- src/modules/land-works/components/land-works-selected-feature-card/index.tsx
- src/modules/land-works/components/list-new-property/index.tsx
* show approval modal when approving an estate
Fixes #379 
**Checklist**
> fix(estate-approve): show modal

- src/modules/land-works/components/lands-my-properties-header/styled.tsx
fix styles
Fixes #337 
**Checklist**
> [FIX] 337 my properties tab position

- src/modules/land-works/components/list-new-property/index.tsx
fix error message, negative value
Fixes #377
**Checklist**
> 377 / list property input validating

- src/modules/land-works/components/lands-explore-filters/index.tsx
The Mine Only toggle controls the Available Only toggle
Fixes #391 
**Checklist**
> 391 / fix "mine only" toggler

- src/modules/land-works/components/land-works-card/index.scss
status label cursor 
Fixes #394
**Checklist**
>  394 / status label cursor

- src/modules/land-works/views/my-properties-view/index.tsx
> Fix property skeleton loading bug

- package.json
- src/api/notion/client.tsx
- src/config.ts
- src/layout/index.tsx
> feat: notion db & page fetching

- src/design-system/Tooltip/tooltip-styles.ts
- src/modules/land-works/components/land-works-card-single-view/index.tsx
redesign toolip
Fixes #400 
**Checklist**
> 400 / tooltip styles

- src/modules/land-works/api.ts
- src/modules/land-works/components/lands-rent-modal/index.tsx
- src/modules/land-works/contracts/core/LandWorksContract.ts
- src/modules/land-works/contracts/core/abi.json
* set max rent start upon renting
* update ABI to latest
Fixes #none
**Checklist**
> feat(rent): set max rent start

- src/modules/land-works/api.ts
- src/modules/land-works/views/explore-view/index.tsx
Count explore properties, toggled mine only & available
Fixes #414, #415 
need to test it well
**Checklist**
> 414 , 415 / fix explore filters

- src/modules/land-works/components/lands-explore-list/index.tsx
saving scroll position & lands count in session storage
Fixes #410
**Checklist**
> 410 / saving scroll position & lands count in session storage

- src/modules/land-works/views/my-properties-view/index.tsx
Update properties when changing accounts
Fixes #412 
**Checklist**
> 412 / update properties

- src/modules/land-works/views/explore-view/index.tsx
Remove delisted lands from available count
Fixes #415 
**Checklist**
> [FIX] 415 / lands count

- src/modules/land-works/components/list-new-property/index.tsx
Fixes #408 
Added a timeout to show the skeleton 1 sec
**Checklist**
> 408 / list property modal

- src/modules/land-works/components/land-works-scene-experts-form/index.tsx
- src/modules/land-works/components/land-works-scene-experts-form/styled.ts
- src/modules/land-works/components/land-works-scene-experts-heading/index.tsx
- src/modules/land-works/index.tsx
- src/modules/land-works/views/scene-expert-form-view/index.tsx
- src/modules/land-works/views/scene-expert-form-view/styled.ts
- src/modules/land-works/views/single-land-view/index.tsx
added scene form page, typedForm
Fixes #309 
**Checklist**
> 309 / scene form page, typedForm

- src/modules/land-works/components/land-works-card/index.tsx
- src/modules/land-works/views/single-land-view/index.tsx
> 432 breadcrumbs history

- src/modules/land-works/components/land-works-card-single-view/index.tsx
Removed rounding price 
Fixes #431 
**Checklist**
> 431 removed rounding price

- src/modules/land-works/components/edit-property/index.tsx
- src/modules/land-works/components/lands-header-nav-mobile/index.tsx
- src/modules/land-works/index.tsx
- src/modules/land-works/views/edit-property-view/index.tsx
- src/modules/land-works/views/lands-view/index.tsx
- src/modules/land-works/views/my-lending-view/index.tsx
- src/modules/land-works/views/my-renting-view/index.tsx
Redirect from old design
Fixes #434 
**Checklist**
> 434 redirect to new design

- src/modules/land-works/components/lands-explore-filters/filters-data.tsx
Remove icons from filter dropdown
Fixes #447 
**Checklist**
> 447 remove icons from filter dropdown

- src/constants/modules.ts
- src/modules/land-works/components/lands-explore-filters/filters-data.tsx
Added properties to explore sort dropdown: recently listed, recently rented
Fixes #448  #449 
**Checklist**
> [448 449]: added properties to explore sort dropdown

- src/modules/land-works/api.ts
- src/modules/land-works/components/lands-explore-filters/filters-data.tsx
- src/modules/land-works/components/lands-explore-filters/index.tsx
- src/modules/land-works/components/lands-my-properties-subheader/index.tsx
- src/modules/land-works/utils.ts
- src/modules/land-works/views/explore-view/index.tsx
- src/modules/land-works/views/lands-view/index.tsx
- src/modules/land-works/views/my-lending-view/index.tsx
- src/modules/land-works/views/my-properties-view/index.tsx
Added metaverse select, properties count in the tab
Fixes #475  #477 #468 #470
**Checklist**
> [475 477] : metaverse switching

- src/modules/land-works/components/land-claim-modal-checkbox/index.tsx
Added metaverse name on claim modal
Fixes #506 
**Checklist**
> [506] added metaverse name

- src/modules/land-works/views/single-scene-expert-view/index.tsx
> remove undefined portfolio items from array

- src/modules/land-works/components/lands-explore-filters/index.tsx
- src/modules/land-works/components/lands-my-properties-subheader/index.tsx
Sort dropdown width
Fixes #385 #508 
**Checklist**
> [385, 508]: dropdown width

- src/modules/land-works/views/single-land-view/index.tsx
> [388] redirect after withdraw

- src/modules/land-works/components/scene-expert-profile/index.tsx
- src/modules/land-works/components/scene-expert-profile/styled.tsx
> 499 - fix gap between scene builder name and type chip

- src/modules/land-works/components/land-works-table-input/index.tsx
- src/modules/land-works/components/lands-modal-loading/index.scss
- src/modules/land-works/components/lands-modal-loading/index.tsx
- src/modules/land-works/components/lands-modal-success/index.scss
- src/modules/land-works/components/lands-rent-modal/index.tsx
similar to # 453, but for rent and update operator
Fixes #<issue number>
**Checklist**
> [FIX] rent modal messages, modal sizes

- src/modules/land-works/api.ts
- src/modules/land-works/components/lands-claim-modal/index.tsx
- src/modules/land-works/components/lands-my-properties-header/index.tsx
Display all unclaimed rents regardless of metaverse
Fixes #480 
**Checklist**
> [480] added list of all unclaimed properties

- src/modules/land-works/components/lands-explore-list/index.tsx
- src/modules/land-works/components/lands-explore-list/styled.tsx
fixed aspect-ratio view
Fixes #502 
**Checklist**
> [502] fixed aspect-ratio view

- src/modules/land-works/components/land-works-scene-experts-heading/index.tsx
- src/modules/land-works/views/scene-expert-view/index.tsx
> 523 - Fix scroll behaviour

- src/modules/land-works/components/lands-banner-claim-rents/index.tsx
- src/modules/land-works/components/lands-banner-claim-rents/styled.tsx
- src/modules/land-works/components/lands-list-modal/index.tsx
- src/modules/land-works/components/lands-my-properties-header/index.tsx
- src/modules/land-works/components/list-new-property/index.tsx
Added list new property button on My properties page
Fixes #507 
**Checklist**
> [507] : list new property button

- src/modules/land-works/components/scene-expert-card/index.tsx
- src/utils.ts
> 497 - Format short description

- src/modules/land-works/components/lands-my-properties-header/index.tsx
fix claim button display 
Fixes #
**Checklist**
> [FIX] : display claim button

- src/api/notion/client.tsx
> 492 - Sort builders by id

- src/modules/land-works/components/lands-explore-filters/index.tsx
- src/modules/land-works/components/lands-explore-list/index.tsx
- src/modules/land-works/components/lands-my-properties-subheader/index.tsx
- src/modules/land-works/views/explore-view/index.tsx
- src/modules/land-works/views/my-properties-view/index.tsx
save general metaverse
Fixes #537 
**Checklist**
> [537] : save general metaverse

- src/modules/land-works/components/lands-explore-navigator-info/index.tsx
> [530] hiding type prop

- src/wallets/wallet.tsx
Hide disclaimer for beta software upon wallet connection. #529
Fixes #529 
**Checklist**
> [529] remove beta warning

- src/modules/land-works/components/lands-list-modal/index.tsx
- src/modules/land-works/components/list-new-property/index.tsx
Filter properties by metaverse after redirect
Fixes #538 
**Checklist**
> [538] : redirect after listing & filtering

- src/modules/land-works/components/scene-builder-card/index.tsx
> 498 - cover image

- src/modules/interface.tsx
- src/modules/land-works/components/land-works-list-card/index.tsx
- src/modules/land-works/components/list-new-property/index.tsx
- src/modules/land-works/contracts/cryptovoxels/CryptoVoxelsContract.ts
Fixes #534 & #474
**Checklist**
> 534 - fix listing modal

- src/modules/land-works/components/lands-explore-navigator-info/index.tsx
[444] add ens name support to dynamic info map Owner name
Fixes #444 
**Checklist**
> [444] add ens name support to dynamic info map Owner name

- src/modules/land-works/components/list-new-property/index.tsx
- src/modules/land-works/contracts/erc721/ERC721Contract.ts
- src/modules/land-works/views/list-property-view/index.tsx
> feat(list): use isApprovedForAll instead of getApproved

- src/modules/land-works/components/scene-builder-profile/index.tsx
> update conditions for rendering email

- src/modules/land-works/components/scene-builder-profile/scene-builder-details/index.tsx
> 561 -  scene builder container height

- src/modules/land-works/components/land-works-list-card/index.tsx
- src/modules/land-works/components/land-works-list-card/s.module.scss
- src/modules/land-works/components/land-works-selected-feature-card/index.tsx
- src/modules/land-works/components/land-works-selected-feature-card/s.module.scss
> 565 - fix image in modal

- src/modules/land-works/components/land-works-card-single-view/index.scss
> 564 - fix modal colors

- src/modules/land-works/components/list-new-property/index.tsx
Preselect metaverse
Fixes #566 
**Checklist**
> [566] : preselect metaverse

- src/modules/land-works/components/lands-explore-list/index.tsx
Count of explore properties
Fixes #568 
**Checklist**
> [568] : count of explore properties

- src/modules/land-works/components/list-new-property/index.tsx
Fix default value
Fixes #566 
**Checklist**
> [FIX]: 566 fix default value

- src/modules/land-works/components/scene-builder-profile/index.tsx
- src/modules/land-works/components/scene-builder-profile/styled.tsx
> Scene builder cover fix

- src/modules/land-works/components/lands-explore-list/index.tsx
- src/modules/land-works/views/explore-view/explore-view.scss
- src/modules/land-works/views/explore-view/index.tsx
Hide explore subheader on scroll
Fixes #601 
**Checklist**
> [601]: hide explore subheader on scroll

- src/modules/land-works/components/edit-property/index.tsx
- src/modules/land-works/views/single-land-view/index.tsx
Currency value on edit modal is equal asset currency
Fixes #604 
**Checklist**
> [604] : default currency value on edit modal

- src/modules/land-works/components/land-parcel-properties/index.tsx
> 603 - voxels link

- src/modules/land-works/views/my-properties-view/index.tsx
My properties search functional
Fixes #612 
**Checklist**
> [612] : my properties search

- src/modules/land-works/components/lands-map-overlay/index.tsx
- src/modules/land-works/components/lands-map-overlay/styled.tsx
Fixes #<issue number>
I've merged the branch for the changes on #599 into this branch because I want to avoid conflict
**Checklist**
> 618 - Voxel labels

- src/modules/land-works/api.ts
- src/modules/land-works/components/lands-explore-list/index.tsx
- src/modules/land-works/components/lands-explore-map/index.tsx
- src/modules/land-works/providers/lands-map-tiles/index.tsx
- src/modules/land-works/views/explore-view/index.tsx
Border for lands on Decentraland map
Fixes #592 
**Checklist**
> [592]: border for lands on map

- src/modules/land-works/components/land-works-card-single-view/index.tsx
> 617 - styling bug

- src/modules/land-works/views/explore-view/index.tsx
Remember map view
Fixes #613 
**Checklist**
> [613]: remember map view

- src/modules/land-works/api.ts
- src/modules/land-works/components/land-parcel-properties/index.tsx
- src/modules/land-works/views/single-land-view/index.tsx
Decentraland additional property
Fixes #621 
**Checklist**
> [621]: Decentraland additional property

- src/modules/land-works/utils.ts
- src/modules/land-works/views/my-properties-view/index.tsx
Fixed search logic & filtered by query lands count
Fixes #612
**Checklist**
> [612]: search logic

- src/modules/land-works/views/explore-view/explore-view.scss
removed animation of hide
Fixes #601 
**Checklist**
> [601]: removed animation of hide

- src/modules/land-works/components/lands-map-overlay/styled.tsx
fix min tooltip width
Fixes #624 
**Checklist**
> [624]: coordinates tooltip

- src/modules/land-works/components/lands-map-overlay/index.tsx
- src/modules/land-works/components/lands-map-overlay/styled.tsx
Restyle Voxels additional info
Fixes #618 
**Checklist**
> [618]: voxels additional info restyle

- src/modules/land-works/components/lands-explore-map/index.tsx
Explore map lands border
Fixes #592 
**Checklist**
> [592]: map land border

- src/modules/land-works/constants.ts
- src/wallets/components/notifications/data.tsx
Changed tweet text from notification 
Fixes #554 
**Checklist**
> [554]: promote notification text

- src/wallets/components/notifications/NotificationMessage.tsx
- src/wallets/components/notifications/index.tsx
- src/wallets/components/notifications/styled.ts
fix some bugs
Fixes #253 
**Checklist**
> [253]: notifications bugs

- src/modules/land-works/components/land-works-card-single-view/index.scss
- src/modules/land-works/components/land-works-card-single-view/index.tsx
- src/modules/land-works/components/land-works-card-single-view/styled.ts
Fixes #479 #636 
**Checklist**
> [479, 636]: property contacts

- src/modules/land-works/components/lands-explore-filters/filters-data.tsx
- src/modules/land-works/components/lands-explore-filters/index.tsx
- src/modules/land-works/constants.ts
- src/modules/land-works/views/explore-view/index.tsx
- src/utils.ts
> [586]: sort properties

- src/modules/land-works/components/lands-map-overlay/styled.tsx
min width, word elipsis
Fixes #629 
**Checklist**
> [628]: additional info

- src/modules/land-works/components/land-works-list-new-summary/index.tsx
dynamic rent price on edit modal
Fixes #632 
**Checklist**
> [632]: dynamic rent price

- src/design-system/Checkbox/checkbox-style.ts
- src/modules/land-works/components/land-claim-modal-checkbox/index.scss
- src/modules/land-works/components/land-claim-modal-checkbox/index.tsx
- src/modules/land-works/components/land-works-card-single-view/index.tsx
- src/modules/land-works/components/lands-claim-modal/index.scss
restyle & tooltip error fix
Fixes #635 
**Checklist**
> [635]: claim modal redesign

- src/modules/land-works/components/lands-map-overlay/styled.tsx
Single view coordinates tooltip min width
Fixes #618 
**Checklist**
> [618]: tooltip min width

- src/modules/land-works/components/lands-map-overlay/index.tsx
- src/modules/land-works/components/lands-map-overlay/styled.tsx
Fixes #599 #624 
**Checklist**
> [599, 624]: property coordinates

- src/modules/land-works/components/land-works-card-single-view/index.scss
Aligned buttons 
Fixes #636 
**Checklist**
> [636]: property connect

- src/wallets/components/notifications/NotificationMessage.tsx
Notification style when the number of characters > 40
Fixes
> [FIX]: notification animation style

- src/design-system/Modal/modal-styles.ts
- src/modules/land-works/components/land-works-table-input/styled.ts
- src/modules/land-works/components/lands-list-modal/index.scss
- src/modules/land-works/components/lands-list-modal/index.tsx
- src/modules/land-works/components/lands-modal-loading/index.scss
- src/modules/land-works/components/lands-modal-success/index.scss
- src/modules/land-works/components/lands-rent-date-picker/index.scss
- src/modules/land-works/components/lands-rent-modal/index.scss
- src/modules/land-works/components/lands-rent-modal/index.tsx
- src/wallets/components/connect-wallet-modal/index.tsx
- src/wallets/components/connect-wallet-modal/s.module.scss
popup restyle
Fixes #640 #634 
**Checklist**
> [640,634]: popup restyle

- src/modules/land-works/components/land-works-card-single-view/index.tsx
> [479]: disable chat button

- src/modules/land-works/components/land-claim-history/index.tsx
- src/modules/land-works/components/land-claim-history/styled.tsx
- src/modules/land-works/components/land-my-properties-history/index.tsx
- src/modules/land-works/components/land-my-properties-history/styled.tsx
- src/modules/land-works/components/land-works-card-history/index.tsx
- src/modules/land-works/components/land-works-card-history/styled.tsx
- src/modules/land-works/components/land-works-table-price/index.scss
- src/modules/land-works/components/land-works-table-price/index.tsx
tables style fix
Fixes #627 
**Checklist**
> [627]: history tables style fixes

- src/modules/land-works/components/land-parcel-properties/index.tsx
Restyle
Fixes #621 
**Checklist**
> [621]: additional property style

- src/modules/land-works/components/lands-claim-modal/index.tsx
Claim rent modal warning title text
Fixes #635 
**Checklist**
> [635]: warning title text

- src/wallets/components/notifications/utils.ts
notifications button status
Fixes #551 
**Checklist**
> [551]: notifications button

- src/wallets/components/notifications/utils.ts
> [FIX]: 551 land availability

- src/modules/land-works/components/lands-rent-date-picker/index.scss
fixed position of dash between dates and input width
Fixes #634 
**Checklist**
> [634]: position of dash between dates

- src/modules/land-works/components/lands-explore-list/index.tsx
- src/modules/land-works/views/explore-view/explore-view.scss
- src/modules/land-works/views/explore-view/index.tsx
added scroll and removed animation
Fixes #601 
**Checklist**
> [601]: explore page header position

- src/modules/land-works/components/land-parcel-properties/index.tsx
parcel properties width
Fixes #621 
**Checklist**
> [621]: parcel properties width

- src/wallets/components/notifications/utils.ts
button status
Fixes #551
**Checklist**
> [551]: button status

- src/wallets/components/notifications/NotificationMessage.tsx
- src/wallets/components/notifications/styled.ts
- src/wallets/components/notifications/utils.ts
notification text animation
Fixes #253 
**Checklist**
> [253]: notification text animation

- src/wallets/components/notifications/NotificationMessage.tsx
- src/wallets/components/notifications/utils.ts
> [253]: fix notification animation

- src/modules/land-works/api.ts
- src/modules/land-works/constants.ts
- src/modules/land-works/views/explore-view/index.tsx
> [653]: mine only lands

- src/design-system/Modal/modal-styles.ts
> [670]: list modal max height

- src/design-system/ControlledSelect/ControlledSelect.tsx
- src/design-system/ControlledSelect/styled.ts
- src/modules/land-works/api.ts
- src/modules/land-works/components/lands-explore-filters/filters-data.tsx
- src/modules/land-works/components/lands-explore-filters/index.tsx
- src/modules/land-works/views/explore-view/index.tsx
> [662]: available dropdown

- src/modules/land-works/components/lands-map-overlay/index.tsx
- src/modules/land-works/components/lands-map-overlay/styled.tsx
> [694]: coordinates tooltip

- src/modules/land-works/views/explore-view/index.tsx
explore sort 
Fixes #598 #688 
**Checklist**
> [688]: hottest first sort

- src/design-system/ControlledSelect/ControlledSelect.tsx
- src/design-system/ControlledSelect/styled.ts
- src/modules/land-works/components/lands-explore-filters/index.tsx
> [662]: select static placeholder

- src/design-system/Tooltip/Tooltip.tsx
- src/design-system/Tooltip/tooltip-styles.ts
- src/modules/land-works/components/lands-input-rent-period/index.scss
- src/modules/land-works/components/lands-input-rent-period/index.tsx
> [698]: list modal tooltip

- src/design-system/Tooltip/tooltip-styles.ts
- src/modules/land-works/components/lands-explore-map-voxels/index.tsx
- src/modules/land-works/components/price-popover/index.tsx
- src/modules/land-works/views/explore-view/index.tsx
- src/utils.ts
- src/wallets/components/notifications/utils.ts
> [FIX]: console warnings

- src/modules/land-works/components/land-parcel-properties/index.tsx
> [716] decentraland details

- src/modules/land-works/components/lands-rent-date-picker/index.tsx
> [708]: rent modal tooltip

- src/modules/land-works/components/lands-explore-list/index.tsx
> [707]: explore scroll

- src/modules/land-works/components/price-popover/index.tsx
- src/modules/land-works/components/price-popover/styled.ts
> [659]: price filter

- src/modules/landing/components/Advantages/index.tsx
- src/modules/landing/components/hero/index.scss
- src/modules/landing/components/hero/index.tsx
> [654]: landing page fix

- src/modules/land-works/components/lands-rent-date-picker/index.tsx
> [708]: rent modal tooltip text

- src/modules/scene-builder/components/scene-builder-description-readmore/index.tsx
- src/modules/scene-builder/components/scene-builder-profile/scene-builder-portfolio/index.tsx
> [711]: builder description

- src/modules/landing/components/Advantages/index.tsx
- src/modules/landing/components/Connect/index.tsx
- src/modules/landing/components/Explore/styled.ts
- src/modules/landing/components/FAQ/styled.tsx
- src/modules/landing/components/about/index.tsx
- src/modules/landing/components/hero/index.scss
Fixes #654 #697 
**Checklist**
> [654, 697]: landing

- src/modules/faq/components/CanIContact.tsx
- src/modules/faq/components/HowItWorks.tsx
- src/modules/faq/components/HowList.tsx
- src/modules/faq/components/Support.tsx
- src/modules/faq/styled.ts
> [736]: faq page

- src/modules/scene-builder/components/scene-builder-contact-modal/index.tsx
- src/modules/scene-builder/components/scene-builder-profile/index.tsx
- src/modules/scene-builder/components/scene-builder-profile/styled.tsx
> [728]: scene builder

- src/modules/landing/components/FAQ/styled.tsx
> [741]: faq page button icon

- src/modules/land-works/components/lands-explore-filters/styled.ts
- src/modules/land-works/components/lands-explore-subheader/lands-explore-subheader.module.scss
- src/modules/land-works/views/explore-view/explore-view.scss
- src/styles/index.scss
> [743]: explore navigation

- src/layout/components/layout-header/index.tsx
- src/layout/components/layout-header/layout-header.module.scss
- src/modules/land-works/components/land-claim-history/index.tsx
- src/modules/land-works/components/land-my-properties-history/index.tsx
- src/modules/land-works/components/land-parcel-properties/index.tsx
- src/modules/land-works/components/land-works-card-history/index.tsx
- src/modules/land-works/components/lands-search/index.scss
- src/modules/land-works/components/lands-search/index.tsx
- src/wallets/components/connected-wallet/index.tsx
> [721]: ui bugs

- src/modules/land-works/components/land-works-list-new-summary/index.tsx
- src/modules/land-works/components/land-works-selected-feature-coords/index.tsx
- src/modules/land-works/components/lands-input-rent-price/index.tsx
- src/modules/land-works/components/list-new-property/index.tsx
- src/modules/land-works/constants.ts
> [657]: listing modal

- src/modules/interface.tsx
- src/modules/land-works/components/lands-explore-filters-modal/DecentralandModal.tsx
- src/modules/land-works/components/lands-explore-filters-modal/VoxelModal.tsx
- src/modules/land-works/components/lands-explore-filters-modal/styled.ts
- src/modules/land-works/components/lands-explore-filters/index.tsx
> [664]: more filters

- src/styles/index.scss
> [743]: explore map view

- README.md
> docs: update voxels integration

- src/design-system/Modal/modal-styles.ts
- src/modules/land-works/components/land-works-list-card/index.tsx
- src/modules/land-works/components/land-works-list-new-summary/index.tsx
- src/modules/land-works/components/land-works-selected-feature-coords/index.tsx
- src/modules/land-works/components/list-new-property/index.tsx
> [657]: listing modal styles

- src/modules/land-works/components/lands-explore-filters-modal/VoxelModal.tsx
- src/modules/land-works/components/lands-explore-filters/index.tsx
> [660]: voxels more filters

- src/modules/land-works/components/list-new-property/index.tsx
> [657]: fix list modal size & logic

- src/modules/land-works/components/price-popover/index.tsx
> [659]: remember min max price

- src/modules/land-works/components/lands-explore-filters-modal/DecentralandModal.tsx
- src/modules/land-works/components/lands-explore-filters-modal/styled.ts
> [664]: fix decentraland filters

- src/layout/components/layout-header/HeaderAgitationBar.tsx
- src/modules/grants-program/components/jury-and-scoring-section/index.tsx
Fixes #805 
Fixes last comment of the task #781 (close button is not aligned)
**Checklist**
> [781, 805] Add additional guidelines section on grand program page and align content of the agitation bar

- src/design-system/Modal/Modal.tsx
- src/design-system/Modal/modal-styles.ts
- src/layout/components/layout-header/HeaderActionButton.tsx
- src/layout/components/layout-header/HeaderRight.tsx
- src/modules/land-works/api.ts
- src/modules/land-works/components/land-parcel-properties/index.tsx
- src/modules/land-works/components/lands-explore-filters-modal/DecentralandModal.tsx
- src/modules/land-works/components/lands-explore-filters-modal/VoxelModal.tsx
- src/modules/land-works/components/lands-rent-modal/index.tsx
- src/modules/landing/index.tsx
- src/modules/scene-builder/components/scene-builder-profile/scene-builder-portfolio/index.tsx
- src/wallets/components/connected-wallet/index.tsx
Fixes #755
Fixes #774
Fixes #784
Fixes #785
Fixes #810
**Checklist**
> [755, 774, 784, 785, 810]: Bug fixes 

- src/components/custom/cards-grid/index.tsx
- src/hooks/useGetIsMounted.ts
- src/modules/land-works/components/land-works-card-explore-view/index.tsx
- src/modules/land-works/components/lands-explore-list/index.tsx
- src/modules/land-works/views/explore-view/ExploreMap.tsx
- src/modules/land-works/views/explore-view/index.tsx
- src/modules/land-works/views/my-properties-view/index.tsx
Fixes #828
Fixes card sizes on 'My properties' page
Fixes cards shifting when toggling map visibility  
**Checklist**
> [828]: Map inconsistency

- src/modules/land-works/components/land-works-card-availability/index.tsx
- src/modules/land-works/utils.ts
Fixes #830
Fixes #829
**Checklist**
> [829, 830]: Incorrect additional filters logic

- src/modules/land-works/components/land-works-card-availability/index.tsx
- src/modules/land-works/components/lands-explore-filters/rent-status-select.tsx
- src/modules/land-works/components/lands-explore-list/index.tsx
- src/modules/land-works/components/lands-explore-list/useNumberOfLoadedCards.ts
- src/modules/land-works/components/price-popover/index.tsx
- src/modules/land-works/components/price-popover/usePriceQueryParams.ts
- src/modules/land-works/views/explore-view/index.tsx
Fixes last comment in task #812
Fixes last comment in task #828
Fixes last comment in task #829
**Checklist**
> [812, 828, 829]: Fix small issues

- src/modules/land-works/views/explore-view/index.tsx
> [845] Fix infinite loading on explore page

- src/modules/grants-program/components/content/index.tsx
- src/modules/grants-program/components/hero/index.tsx
- src/modules/grants-program/index.tsx
> [856]: Update grants program page

- src/modules/land-works/components/land-works-card-explore-view/index.tsx
- src/modules/land-works/components/lands-explore-list/index.tsx
- src/modules/land-works/views/my-properties-view/index.tsx
- src/modules/land-works/views/single-land-view/index.tsx
- src/router/routes.ts
- src/wallets/components/notifications/data.tsx
> [852]: Fix broken links on property page

- src/modules/grants-program/components/hero/index.tsx
Fixes last comment in task #856
**Checklist**
> [856]: Update last sentence in hero section on grant program page

- src/layout/index.tsx
- src/modules/land-works/components/lands-list-modal/index.tsx
- src/modules/land-works/views/not-found-view/index.tsx
- src/modules/land-works/views/single-land-view/index.tsx
- src/router/routes.ts
- src/wallets/components/notifications/data.tsx
* Redirects old path to new to not break previous links
Fixes #none
**Checklist**
> fix: redirect old path

- src/layout/components/quastion-accordion/QuestionAccordion.tsx
- src/layout/components/quastion-accordion/styled.tsx
- src/modules/faq/index.tsx
- src/modules/faq/styled.ts
> [759]: FAQ page adaptive

- src/modules/grants-program/components/hero/index.tsx
> [868]: Fix grant program's page hero section spacings

- src/layout/components/layout-header/HeaderNavLinks.tsx
- src/layout/index.tsx
- src/modules/land-works/components/list-new-property/index.tsx
- src/router/routes.ts
- src/wallets/components/notifications/data.tsx
> [861]: Fix path to my properties page; Add redirect to my properties page

- src/modules/land-works/contracts/core/LandWorksContract.ts
- src/modules/land-works/contracts/core/abi.json
> feat: referrals

- package-lock.json
- package.json
- src/index.tsx
- src/wallets/wallet.tsx
> [837]: Add slitpbee analytics

- src/layout/components/layout-header/HeaderRight.tsx
- src/modules/land-works/api.ts
- src/modules/land-works/components/land-works-card-single-view/index.tsx
- src/modules/land-works/components/lands-banner-claim-rents/index.tsx
- src/modules/land-works/components/lands-my-properties-header/index.tsx
- src/modules/land-works/utils.ts
- src/modules/land-works/views/my-properties-view/index.tsx
- src/modules/land-works/views/single-land-view/index.tsx
- src/modules/landing/components/hero/index.tsx
- src/wallets/components/connected-wallet/index.tsx
Fixes #860
Fixes #892
Fixes #883
**Checklist**
> [860, 883, 892]: Fix loading animations and add splitbee click events

- src/hocs/withSplitBee.tsx
- src/layout/metric/SplitBeeListButton.tsx
- src/modules/land-works/components/land-works-grid-empty-state/index.tsx
- src/modules/land-works/components/lands-explore-list/index.tsx
- src/modules/land-works/components/lands-my-properties-header/index.tsx
- src/modules/land-works/index.tsx
- src/modules/land-works/views/explore-view/index.tsx
- src/modules/land-works/views/my-properties-view/index.tsx
- src/providers/listing-modal-provider/ListingModalProvider.tsx
- src/providers/listing-modal-provider/index.ts
- src/utils/context.ts
…racking for all list new property buttons
Fixes #915
**Checklist**
> [915]: Return button for listing new properties on explore page and add split bee tracking for buttons for all listing new properties

- .eslintrc
- src/design-system/ControlledSelect/ControlledSelect.tsx
- src/design-system/ControlledSelect/styled.ts
- src/helpers/helpers.ts
- src/hocs/withSplitBee.tsx
- src/modules/land-works/components/land-works-grid-empty-state/index.tsx
- src/modules/land-works/components/land-works-input/index.tsx
- src/modules/land-works/components/lands-explore-filters/index.tsx
- src/modules/land-works/components/lands-explore-list/index.tsx
- src/modules/land-works/components/lands-my-properties-header/index.tsx
- src/modules/land-works/components/list-new-property/index.tsx
- src/modules/land-works/providers/contract-provider/index.tsx
- src/modules/land-works/utils.ts
- src/modules/land-works/views/my-properties-view/ListAssetCard.tsx
- src/modules/land-works/views/my-properties-view/ListedTabContent.tsx
- src/modules/land-works/views/my-properties-view/MyPropertiesViewHeader.tsx
- src/modules/land-works/views/my-properties-view/NotListedTabContent.tsx
- src/modules/land-works/views/my-properties-view/RentedTabContent.tsx
- src/modules/land-works/views/my-properties-view/SortSelect.tsx
- src/modules/land-works/views/my-properties-view/index.tsx
- src/modules/land-works/views/my-properties-view/useGetAccountAssetsQuery.ts
- src/modules/land-works/views/my-properties-view/useGetAccountNotListedAssets.ts
- src/providers/listing-modal-provider/ListingModalProvider.tsx
- tsconfig.json
Fixes #906 
Fixes #912
**Checklist**
> [906, 912]: Not listed assets tab and cards

- src/modules/land-works/components/list-new-property/index.tsx
- src/modules/land-works/views/my-properties-view/index.tsx
Fixes #919 
Fixes #920 
**Checklist**
> [919, 920]: Reorder tabs and fix select width

- src/layout/components/info-alert/InfoAlert.tsx
- src/layout/components/info-alert/index.ts
- src/modules/land-works/views/my-properties-view/ClaimRewardsAlert.tsx
- src/modules/land-works/views/my-properties-view/index.tsx
- src/modules/land-works/views/my-properties-view/useGetAccountAssetsQuery.ts
> [926]: Return claim alert

- src/design-system/ControlledSelect/styled.ts
- src/modules/land-works/components/price-popover/index.tsx
- src/modules/land-works/components/price-popover/styled.ts
> [788]: Flip select arrow is it's active

- src/modules/faq/components/CanIContact.tsx
> [742]: Add faq links

- src/modules/land-works/components/price-popover/index.tsx
- src/modules/land-works/components/price-popover/styled.tsx
> [754]: Update price popup ui

- src/modules/land-works/components/land-works-card-single-view/AdsToggle.tsx
- src/modules/land-works/components/land-works-card-single-view/index.tsx
- src/web3/token.ts
Fixes last comment of the task #886
**Checklist**
> [886]: Add ads toggle msg and change tooltip text

- src/modules/land-works/components/land-works-list-new-summary/index.tsx
- src/modules/land-works/components/list-new-property/index.tsx
> [944]: Add different scene detail on summary step for listing if advertisement enabled

- src/modules/land-works/components/lands-explore-filters-modal/DecentralandModal.tsx
- src/modules/land-works/utils.ts
> [945]: Fix more filter distance slider

- src/components/styled/stepper/StepIcon.tsx
- src/components/styled/stepper/StepLabel.tsx
- src/components/styled/stepper/Stepper.tsx
- src/components/styled/stepper/index.ts
- src/modules/land-works/components/list-new-property/index.tsx
Fixes last comment for task #885 
**Checklist**
> [885]: Fix stepper; Remove ads for cryptovoxels; Set ads by default

- src/modules/land-works/components/land-claim-rents-alert/ClaimRewardsAlert.tsx
- src/modules/land-works/components/land-claim-rents-alert/ClaimRewardsModal.tsx
- src/modules/land-works/components/land-claim-rents-alert/ClaimRewardsModalAdsTab.tsx
- src/modules/land-works/components/land-claim-rents-alert/ClaimRewardsModalRentsTab.tsx
- src/modules/land-works/components/land-claim-rents-alert/ClaimRewardsProvider.tsx
- src/modules/land-works/contracts/rewards/AdsRewardsContract.ts
- src/styles/index.scss
Fixes [#888](https://github.com/EnterDAO/LandWorks-FE/issues/888#issuecomment-1327140879)
Fixes [#930](https://github.com/EnterDAO/LandWorks-FE/issues/930#issuecomment-1327122265)
**Checklist**
> [888]: Fix rewards bugs

- src/modules/land-works/components/land-works-card-single-view/index.scss
- src/modules/land-works/components/land-works-card-single-view/index.tsx
- src/modules/land-works/components/list-new-property/index.tsx
Fixes comment [#1328716475](https://github.com/EnterDAO/LandWorks-FE/issues/885#issuecomment-1328716475) for #885
Fixes comment [#1328712154](https://github.com/EnterDAO/LandWorks-FE/issues/886#issuecomment-1328712154) and [#1327151204](https://github.com/EnterDAO/LandWorks-FE/issues/886#issuecomment-1327151204) for #886
**Checklist**
> [885, 886]: Add ads step in listing modal based on metaverse

- src/layout/components/info-alert/InfoAlert.tsx
- src/modules/land-works/components/land-works-card-single-view/CountdownBanner.tsx
- src/modules/land-works/components/land-works-card-single-view/index.tsx
> [955]: Fix countdown bugs

- package-lock.json
- src/modules/land-works/components/edit-property/index.tsx
- src/modules/land-works/components/land-works-input/index.tsx
- src/modules/land-works/components/land-works-input/input-styles.ts
- src/modules/land-works/components/land-works-input/s.module.scss
- src/modules/land-works/components/land-works-list-new-summary/index.tsx
- src/modules/land-works/components/lands-input-rent-price/index.tsx
- src/modules/land-works/components/list-new-property/index.tsx
- src/wallets/components/connect-wallet-modal/index.tsx
- src/wallets/wallet.tsx
- src/web3/utils.ts
Fixes #880 
Fixes #953 
Fixes #954 
Fixes #956
**Checklist**
> [880, 953, 954, 956]: Fix listing modal bugs

- src/layout/components/load-more-button/useLoadMoreButton.ts
- src/modules/land-works/components/land-works-card-single-view/index.tsx
- src/modules/land-works/components/lands-explore-list/index.tsx
- src/modules/land-works/components/lands-explore-map-voxels/index.tsx
- src/modules/land-works/utils.ts
- src/modules/land-works/views/explore-view/ExploreMap.tsx
- src/modules/land-works/views/explore-view/index.tsx
> [960]: Fix map bugs

- src/components/custom/small-amount-tooltip/index.tsx
- src/modules/land-works/components/land-claim-rents-alert/ClaimRewardsModalAdsTab.tsx
- src/modules/land-works/components/land-works-card-explore-view/index.scss
- src/modules/land-works/components/lands-input-rent-price/index.tsx
- src/modules/land-works/views/single-land-view/index.tsx
Fixes #888
Fixes #953 
Fixes #955
**Checklist**
> [888,953,955]: Fix blinking claim rent button and overflowing total rent price in listing modal

- src/modules/interface.tsx
- src/modules/land-works/components/atlas/index.tsx
- src/modules/land-works/components/lands-explore-map/LandTooltip.tsx
- src/modules/land-works/components/lands-explore-map/LandTooltipContent.tsx
- src/modules/land-works/components/lands-explore-map/index.tsx
- src/modules/land-works/views/explore-view/ExploreMap.tsx
- src/utils.ts
Fixes #961
Fixes #744
**Checklist**
> [744, 961]: Add tooltips for decentraland map

- src/design-system/ControlledSelect/ControlledSelect.tsx
- src/layout/components/load-more-button/useLoadMoreButton.ts
- src/modules/interface.tsx
- src/modules/land-works/components/lands-explore-filters/filters-data.tsx
> [986]: Add tooltip for filter option on explore page

- src/design-system/Modal/modal-styles.ts
- src/modules/land-works/components/edit-property/index.scss
- src/modules/land-works/components/edit-property/index.tsx
- src/modules/land-works/components/lands-input-rent-period/index.scss
- src/modules/land-works/components/lands-input-rent-period/index.tsx
- src/modules/land-works/components/lands-input-rent-price/index.scss
- src/modules/land-works/components/lands-input-rent-price/index.tsx
- src/modules/land-works/components/list-new-property/AssetList.tsx
- src/modules/land-works/components/list-new-property/LoadingAssetList.tsx
- src/modules/land-works/components/list-new-property/index.scss
- src/modules/land-works/components/list-new-property/index.tsx
- src/modules/land-works/views/my-properties-view/ListAssetCard.tsx
- src/providers/listing-modal-provider/ListingModalProvider.tsx
- src/themes/theme.ts
- src/types.d.ts
> [987]: Add adaptive for listing modal

- src/wallets/components/connected-wallet/index.tsx
- src/wallets/wallet.tsx
Fixes #998 
Fixes #999
**Checklist**
> [998, 999] Fix displaced wallet status popup after user disconnects and connects; Make wallet connection persistent accros tabs

- src/api/notion/client.tsx
- src/components/custom/cards-grid/index.tsx
- src/components/custom/divider/Divider.tsx
- src/components/custom/divider/index.ts
- src/components/custom/skeleton/Skeleton.tsx
- src/components/custom/skeleton/index.ts
- src/modules/land-works/components/land-works-card-explore-view/PropertyCardSkeleton.tsx
- src/modules/land-works/components/land-works-card-explore-view/index.tsx
- src/modules/land-works/components/lands-explore-list/index.tsx
- src/modules/land-works/views/my-properties-view/index.tsx
- src/modules/scene-builder/components/land-works-scene-builders-heading/index.tsx
- src/modules/scene-builder/components/scene-builder-card/SceneBuilderCardSkeleton.tsx
- src/modules/scene-builder/components/scene-builder-card/index.tsx
- src/modules/scene-builder/components/scene-builder-card/styled.tsx
- src/modules/scene-builder/components/scene-builder-card/types.ts
- src/modules/scene-builder/components/scene-builder-tabs/index.tsx
- src/modules/scene-builder/components/scene-builder-tabs/styled.tsx
- src/modules/scene-builder/constants.ts
- src/modules/scene-builder/utils.ts
- src/modules/scene-builder/views/scene-builder-view/index.tsx
- src/modules/scene-builder/views/single-scene-builder-view/index.tsx
- src/utils.ts
> [996]: Change skeleton loading on explore, my properties and scene builders pages; Improve data loading on scene builder page

- package-lock.json
- package.json
- src/components/common/TextField/TextField.tsx
- src/components/common/TextField/index.ts
- src/design-system/Button/button-styles.ts
- src/modules/land-works/components/lands-rent-date-picker/DateTimePickerField/DateTimePickerField.tsx
- src/modules/land-works/components/lands-rent-date-picker/DateTimePickerField/index.ts
- src/modules/land-works/components/lands-rent-date-picker/index.tsx
- src/modules/land-works/components/lands-rent-modal/index.scss
- src/modules/land-works/components/lands-rent-modal/index.tsx
Fixes #1005 
Fixes glowing disabled gradient button
**Checklist**
> [1005]: Fix and update rent datepickers components

- src/themes/theme.ts
- src/types.d.ts
> Fix datepicker theme

- src/design-system/ControlledSelect/styled.ts
- src/modules/land-works/views/my-properties-view/MyPropertiesViewHeader.tsx
- src/modules/land-works/views/my-properties-view/MyPropertiesViewTabs.tsx
- src/modules/land-works/views/my-properties-view/index.tsx
- src/styles/scrollbar.scss
Fixes #1015 
Fixes #1020
**Checklist**
> [1015,1020]: Change position of the tabs on my properties page and change styles of the scrollbar

- src/layout/components/load-more-button/LoadMoreButton.tsx
- src/modules/land-works/views/my-properties-view/MyPropertiesViewTabs.tsx
- src/modules/land-works/views/my-properties-view/index.tsx
- src/modules/land-works/views/my-properties-view/useGetAllAccountAssetsQuery.tsx
- src/router/routes.ts
Fixes #1018 
Fixes #1019
**Checklist**
> [1018, 1019]: Add tab prioritization and remove listed from load more button

- src/providers/listing-modal-provider/ListingModalProvider.tsx
Fixes comment [1372082255](https://github.com/EnterDAO/LandWorks-FE/issues/1015#issuecomment-1372082255) for task #987
**Checklist**
> [987]: Change breakpoints when listing modal should be smaller

- src/hooks/useDebounce.ts
- src/modules/land-works/views/explore-view/MetaverseMap/DecentralandMap/DecentralandMapTileInfo.tsx
Fixes multiple queries for ens name when hovering over map 
**Checklist**
> [744]: Add debounce on ens name fetching when hovering over map 

- src/design-system/Modal/Modal.tsx
- src/modules/land-works/components/lands-list-modal/index.tsx
- src/modules/land-works/components/lands-list-modal/styled.ts
> [1039]: Fix listing modal successful popup

- src/wallets/components/connect-wallet-modal/index.tsx
> [1042]: Add split bee event on sign in

- src/modules/land-works/components/land-table-tx-hash/index.tsx
- src/modules/land-works/components/land-works-card-history/index.tsx
- src/modules/land-works/components/land-works-table-input/index.tsx
- src/modules/land-works/constants.ts
Fixes #1048 
Fixes #1050
**Checklist**
> [1048, 1050]: Fix font size size of the renter in rent history table and fix typos in voxels more filters

- src/hooks/useEnsName.ts
- src/modules/land-works/components/land-works-card-single-view/index.tsx
- src/modules/land-works/views/explore-view/MetaverseMap/DecentralandMap/DecentralandMapTileInfo.tsx
> [1049]: Fix operator address is not updated after changes on property page

- src/layout/components/layout-header/HeaderAgitationBar.tsx
- src/modules/land-works/components/land-claim-rents-alert/ClaimRewardsModalAdsTab.tsx
- src/modules/land-works/components/land-works-card-single-view/EnableAdsModal.tsx
- src/modules/land-works/components/lands-explore-filters-modal/VoxelModal.tsx
- src/modules/land-works/components/lands-modal-success/index.tsx
- src/modules/land-works/components/lands-rent-modal/index.tsx
- src/modules/land-works/components/list-new-property/index.tsx
Fixes #943
Fixes #1060
Fixes #1061
**Checklist**
> [943,1060,1061]: Add link to article about advertisement feature; Fix rent successful modal; Fix more filters for voxels

- src/modules/land-works/views/explore-view/ExploreMap.tsx
> [1067]: Fix issue when open app button disappear after closing it in fullscreen

- src/design-system/ControlledSelect/ControlledSelect.tsx
- src/design-system/ControlledSelect/styled.ts
- src/themes/typography-styles.ts
- src/wallets/components/connected-wallet/index.tsx
Fixes #1069
Fixes #1070
**Checklist**
> [1069, 1070]: Fix cosmetic issues

- src/modules/land-works/views/my-properties-view/useGetAccountAssetsQuery.ts
> [1068]: Fix user properties infinite loading

- src/modules/land-works/components/land-works-list-new-summary/index.tsx
- src/modules/land-works/components/land-works-selected-feature-card/index.tsx
- src/modules/land-works/components/land-works-selected-feature-coords/index.tsx
- src/modules/land-works/components/list-new-property/index.tsx
- src/modules/land-works/contracts/cryptovoxels/CryptoVoxelsContract.ts
> [1066]: Add lands caching

- src/modules/land-works/components/price-popover/index.tsx
- src/modules/land-works/components/price-popover/styled.tsx
> [1065]: Add disabled state for price range fields

- src/layout/components/layout-header/HeaderRight.tsx
- src/wallets/wallet.tsx
Fixes #1080
Fixes #1010
**Checklist**
> [1010, 1080]: Fix issue when metamask opens everytime on reload when wallet is locked

- src/layout/components/layout-header/HeaderNavLinks.tsx
- src/modules/faq/components/FaqCanIHire.tsx
- src/modules/faq/components/FaqSupport.tsx
- src/modules/meta-creators/components/scene-builder-card/index.tsx
- src/modules/meta-creators/components/scene-builder-description-readmore/index.tsx
- src/modules/meta-creators/views/MetaCreatorsCreatorView/MetaCreatorsCreatorView.tsx
- src/modules/meta-creators/views/MetaCreatorsView/MetaCreatorsViewCreators.tsx
- src/modules/meta-creators/views/MetaCreatorsView/MetaCreatorsViewHero.tsx
Fixes additional issues for #1011
Fixes additional issues for #1024
**Checklist**
> [1011, 1024]: Split metacreators in two words; Center cards description; Add discord link; Remove wrapping for read more button 
